dev:            # <profile-name>
  target: dev
  outputs:
    dev:
      dataset: '{{ env_var(''YOUR_DBT_DEV_DATASET'') }}'
      method: oauth
      location: US
      project: henrytxz
      threads: 4
      type: bigquery

audit:
  target: audit
  outputs:
    audit:
      dataset: data_demo_audit
      method: service-account
      keyfile: "{{ env_var('PATH_GCP_KEYFILE') }}"
      location: US
      project: henrytxz
      threads: 4
      type: bigquery

prod:
  target: prod
  outputs:
    audit:
      dataset: data_demo_prod
      method: service-account
      keyfile: "{{ env_var('PATH_GCP_KEYFILE') }}"
      location: US
      project: henrytxz
      threads: 4
      type: bigquery